

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NeuMo.NeuMoDatabase
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class NeuMoEntities : DbContext
{
    public NeuMoEntities()
        : base("name=NeuMoEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tbl_StorageGrid> tbl_StorageGrid { get; set; }

    public virtual DbSet<tbl_FrameNumberPattern> tbl_FrameNumberPattern { get; set; }

    public virtual DbSet<tbl_BikePlacements> tbl_BikePlacements { get; set; }

    public virtual DbSet<tbl_Branches> tbl_Branches { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<tbl_Company> tbl_Company { get; set; }

    public virtual DbSet<tbl_BikePassPrint_Log> tbl_BikePassPrint_Log { get; set; }

    public virtual DbSet<vw_NeumoProductDetails> vw_NeumoProductDetails { get; set; }

    public virtual DbSet<tbl_BrandExtension> tbl_BrandExtension { get; set; }

}

}

