
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NeuMo.NeuMoDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_BikePlacements
{

    public int ID { get; set; }

    public string BoxName { get; set; }

    public bool IsOccupied { get; set; }

    public bool IsPriority { get; set; }

    public string Location { get; set; }

    public System.DateTime DateTime { get; set; }

    public Nullable<int> AssemblerID { get; set; }

    public string Status { get; set; }

    public string BikeID { get; set; }

    public Nullable<System.DateTime> AssembleStartTime { get; set; }

    public Nullable<System.DateTime> AssembleEndTime { get; set; }

    public Nullable<bool> IsDifficult { get; set; }

    public string KeyNumber { get; set; }

    public Nullable<int> UnPackerID { get; set; }

    public string FrameNumber { get; set; }

    public Nullable<bool> IsEbike { get; set; }

    public string CompanyName { get; set; }

    public string Barcode { get; set; }

    public string Mechaniker { get; set; }

}

}
