
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NeuMo.NeuMoDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_BikePassPrint_Log
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string SerialNumber { get; set; }

    public string Barcode { get; set; }

    public string Frame_Num { get; set; }

    public string BranchName { get; set; }

    public string Monteur { get; set; }

    public string AccesoryBag { get; set; }

    public string BatteryNumber { get; set; }

    public string KeyNumber { get; set; }

    public string ForkNumber { get; set; }

    public string CompanyName { get; set; }

    public string Mechaniker { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

}

}
