
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NeuMo.NeuMoDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_StorageGrid
{

    public int ID { get; set; }

    public string BoxName { get; set; }

    public string Company { get; set; }

}

}
