
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NeuMo.NeuMoDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public bool IsAdmin { get; set; }

    public Nullable<bool> IsUnpacker { get; set; }

    public Nullable<bool> IsMechanic { get; set; }

    public bool IsActive { get; set; }

    public string BranchName { get; set; }

    public string CompanyName { get; set; }

    public string EmployeeNumber { get; set; }

    public string BikepassPrinter { get; set; }

    public string LabelPrinter { get; set; }

}

}
