
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NeuMo.NeuMoDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class vw_NeumoProductDetails
{

    public string Company { get; set; }

    public string No_ { get; set; }

    public string Description { get; set; }

    public string Target_Group { get; set; }

    public string Brand { get; set; }

    public string Colour { get; set; }

    public string ColourForName { get; set; }

    public string Frame_Height { get; set; }

    public string Frame_Type { get; set; }

    public string Wheel_Size { get; set; }

    public string Gearshift { get; set; }

    public string Frame_Material { get; set; }

    public string Description_2 { get; set; }

    public string Description_3 { get; set; }

    public string ERFA_No_ { get; set; }

    public string Item_Category_Code { get; set; }

    public byte Blocked { get; set; }

    public string E_Bike_Engine { get; set; }

    public string Leistung { get; set; }

    public decimal Unit_Cost { get; set; }

    public decimal Unit_Price { get; set; }

    public string Model_Year { get; set; }

    public string Bar_Code { get; set; }

    public string EAN { get; set; }

    public Nullable<bool> isebike { get; set; }

    public string E_Bike_Engine_Beschreibung { get; set; }

}

}
